import { Platform } from "react-native";

export const markdownStyles = {
  body: {
    color: "#d4d4d8",
    fontSize: 16,
    lineHeight: 26,
  },
  heading1: {
    color: "#ffffff",
    fontSize: 26,
    fontWeight: "bold" as const,
    marginBottom: 12,
    marginTop: 24,
    borderBottomWidth: 2,
    borderBottomColor: "#3f3f46",
    paddingBottom: 8,
  },
  heading2: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "bold" as const,
    marginBottom: 10,
    marginTop: 20,
  },
  heading3: {
    color: "#3b82f6",
    fontSize: 19,
    fontWeight: "bold" as const,
    marginBottom: 8,
    marginTop: 16,
  },
  heading4: {
    color: "#a1a1aa",
    fontSize: 17,
    fontWeight: "600" as const,
    marginBottom: 6,
    marginTop: 12,
  },
  heading5: {
    color: "#a1a1aa",
    fontSize: 16,
    fontWeight: "600" as const,
    marginBottom: 6,
    marginTop: 10,
  },
  strong: {
    color: "#ffffff",
    fontWeight: "bold" as const,
  },
  em: {
    color: "#d4d4d8",
    fontStyle: "italic" as const,
  },
  bullet_list: {
    marginVertical: 8,
    marginLeft: 4,
  },
  ordered_list: {
    marginVertical: 8,
    marginLeft: 4,
  },
  bullet_list_icon: {
    color: "#3b82f6",
    fontSize: 8,
    marginRight: 8,
    lineHeight: 26,
  },
  ordered_list_icon: {
    color: "#3b82f6",
    fontSize: 16,
    marginRight: 8,
  },
  list_item: {
    marginVertical: 4,
    flexDirection: "row" as const,
  },
  bullet_list_content: {
    flex: 1,
    fontSize: 16,
    lineHeight: 26,
    color: "#d4d4d8",
  },
  ordered_list_content: {
    flex: 1,
    fontSize: 16,
    lineHeight: 26,
    color: "#d4d4d8",
  },
  paragraph: {
    marginTop: 0,
    marginBottom: 12,
  },
  hr: {
    backgroundColor: "#3f3f46",
    height: 2,
    marginVertical: 20,
  },
  blockquote: {
    backgroundColor: "#18181b",
    borderLeftColor: "#3b82f6",
    borderLeftWidth: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginVertical: 12,
    borderRadius: 4,
  },
  code_inline: {
    backgroundColor: "#27272a",
    color: "#f59e0b",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 15,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
  code_block: {
    backgroundColor: "#18181b",
    color: "#f59e0b",
    padding: 16,
    borderRadius: 8,
    fontSize: 14,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    marginVertical: 12,
    borderWidth: 1,
    borderColor: "#27272a",
  },
  fence: {
    backgroundColor: "#18181b",
    color: "#f59e0b",
    padding: 16,
    borderRadius: 8,
    fontSize: 14,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    marginVertical: 12,
    borderWidth: 1,
    borderColor: "#27272a",
  },
  table: {
    borderWidth: 1,
    borderColor: "#3f3f46",
    borderRadius: 8,
    marginVertical: 12,
  },
  thead: {
    backgroundColor: "#27272a",
  },
  tbody: {},
  th: {
    padding: 12,
    borderColor: "#3f3f46",
    borderWidth: 1,
    fontWeight: "bold" as const,
    color: "#ffffff",
  },
  tr: {
    borderBottomWidth: 1,
    borderColor: "#3f3f46",
  },
  td: {
    padding: 12,
    borderColor: "#3f3f46",
    borderWidth: 1,
    color: "#d4d4d8",
  },
  link: {
    color: "#3b82f6",
    textDecorationLine: "underline" as const,
  },
  strikethrough: {
    textDecorationLine: "line-through" as const,
    color: "#71717a",
  },
};
